language: node_js
node_js:
  - "16"
services:
  - xvfb
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - xvfb-run npm install
script:
  - xvfb-run Test:Login