language: node_js
node_js:
  - "16"
addons:
  firefox: stable
before_install:
  - firefox-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run Test:Login