name: QA Challenge QA Github Acions

on:
  push:
    branches:
      - main

jobs:
  Nightwatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: browser-actions/setup-chrome@latest
      - uses: browser-actions/setup-firefox@latest

      - run: npm install
      - run: npm install geckodriver@latest
      - run: npm install chromedriver@latest
      - run: npm ci
      - run: npm run Test:Login
